name: iching
description: "An I Ching app that streamlines the divination process for consultants, turning manual coin flipping into digital magicâ€”because interpreting wisdom should be the hard part, not tossing coins!"
publish_to: 'none'
version: 1.1.2

environment:
  sdk: ^3.5.3

dependencies:
  intl: ^0.17.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10
  pdf: ^3.6.0
  printing: ^5.11.0
  path_provider: ^2.0.11
  permission_handler: ^11.3.0
  collection: ^1.18.0

  # open_file: ^3.0.2
 
  # share_plus: ^6.0.0
  # image_picker: ^0.8.4+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.svg
    - assets/images/logo.jpg
    - assets/images/iching_logo.png
    # - assets/fonts/NotoSans-Regular.ttf
    # - assets/fonts/NotoSans-Bold.ttf
  
flutter_icons:
  android: true
  ios: false
  image_path: assets/images/iching_logo.png
  adaptive_icon_background: "#E6E0E9"
  adaptive_icon_foreground: assets/images/iching_logo.png
